- apt: name={{item}} state=latest force=yes
  with_items:
  - rsync
  - monit

- synchronize: src={{repodir}}/{{item}} dest=/home/{{ansible_ssh_user}}/
  with_items:
  - README.md
  - dc1100.sh
  - LICENSE.txt

- name: monitrc
  synchronize: src={{repodir}}/monit/monitrc dest=/etc/monit/conf.d/airquality

- name: make monit run on boot
  synchronize: src={{repodir}}/monit/monit.service dest=/lib/systemd/system/monit.service

- name: dc1100_wrapper
  synchronize: src={{repodir}}/monit/dc1100_wrapper.sh dest=/home/{{ansible_ssh_user}}

- shell: systemctl daemon-reload
- shell: systemctl enable monit.service
- service: name=monit state=restarted

- timezone: name=America/New_York
